app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['uses' => 'Main\PageController@main', 'as' => 'home']);


Route::get('/finder/{region?}', ['uses' => 'Main\PageController@finder', 'as' => 'finder'])
        ->where('region', '[0-9]+');

// logout any user
Route::get('auth/logout', ['uses' => 'Auth\AuthController@getLogout', 'as' => 'logout']);

/* USER ROUTES */

// user login page
Route::get('auth/login', ['uses' => 'Auth\AuthController@getLogin', 'as' => 'login']);

// user register page
Route::get('auth/register', ['uses' => 'Auth\AuthController@getRegister', 'as' => 'register.page']);

// user register
Route::post('auth/register', ['uses' => 'Auth\AuthController@postRegister', 'as' => 'register']);

// user register success
Route::get('auth/register/success', ['uses' => 'Auth\AuthController@registerSuccess', 'as' => 'register.success']);

// user login page
Route::post('auth/login', ['uses' => 'Auth\AuthController@postLogin', 'as' => 'auth']);

/* PROFILE ROUTES */

// profile page
Route::get('/profile', ['uses' => 'Main\ProfileController@showProfile', 'as' => 'user.profile', 'middleware' => 'auth']);

// profile update user
Route::post('/profile/update/user', ['uses' => 'Main\ProfileController@updateUser', 'as' => 'profile.update_user', 'middleware' => 'auth']);

// profile update user
Route::post('/profile/update/point', ['uses' => 'Main\ProfileController@updatePoint', 'as' => 'profile.update_point', 'middleware' => 'auth']);

// profile change password
Route::post('/profile/change_password', ['uses' => 'Main\ProfileController@changePassword', 'as' => 'profile.change_password', 'middleware' => 'auth']);

// point show
Route::get('point/{point}/show', ['uses' => 'Main\PointController@show', 'as' => 'point.show'])->where('point', '[0-9]+');

// points list
Route::get('point/{pointsType}/{region?}/', ['uses' => 'Main\PointController@index', 'as' => 'point.index'])
        ->where('pointsType', '[0-9]+')
        ->where('region', '[0-9]+');

// points list json
Route::get('/api/point', ['uses' => 'Main\PointController@indexJson', 'as' => 'point.index_json']);

// regions list json
Route::get('/api/region', ['uses' => 'Main\RegionController@indexJson', 'as' => 'region.index_json']);


/* ADMIN ROUTES */

// admin login page
Route::get('admin/login', ['uses' => 'Auth\AuthController@getAdminLogin', 'as' => 'admin.login']);

// admin auth
Route::post('admin/login', ['uses' => 'Auth\AuthController@postAdminLogin', 'as' => 'admin.auth']);

Route::group(['prefix' => 'admin', 'middleware' => 'auth.admin'], function() {

    Route::get('/', ['uses' => 'Main\PageController@adminDashboard', 'as' => 'admin.home']);

    // admin users CRUD
    Route::resource('user', 'Admin\UserController');
    // admin users other
    Route::post('user/{user}/active', ['uses' => 'Admin\UserController@active', 'as' => 'admin.user.active'])->where('user', '[0-9]+');

    // admin points types CRUD
    Route::resource('pointsType', 'Admin\PointsTypeController');

    // admin country CRUD
    Route::resource('country', 'Admin\CountryController');

    // admin region CRUD
    Route::resource('region', 'Admin\RegionController');

    // admin points CRUD
    Route::resource('point', 'Admin\PointController');

    // subscribe
    Route::get('subscribe', ['uses' => 'Admin\SubscribeController@index', 'as' => 'admin.subscribe']);

    // subscribe
    Route::post('subscribe/store', ['uses' => 'Admin\SubscribeController@store', 'as' => 'admin.subscribe.store']);


    Route::get('subscribe/create', ['uses' => 'Admin\SubscribeController@create', 'as' => 'admin.subscribe.create']);

    /*
    * missing routes of admin group
    */
    Route::any('{_missing}', ['uses' => 'Main\PageController@adminNotFound'])
        ->where('_missing', '.*+');
});

app/Models/Region.php
<?php

namespace App\Models;

use App\Models\Traits\CamelCaseAttributes;
use App\Models\PointsType as PointsType;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    use CamelCaseAttributes;

    public static $snakeAttributes = true;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'regions';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['created_at', 'updated_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['country_id', 'name'];

    public function country()
    {
        return $this->belongsTo('App\Models\Country', 'country_id');
    }

    public function points()
    {
        return $this->hasMany('App\Models\Point')->orderBy('name', 'desc');
    }

    public function getNameAttribute($name)
    {
        return mb_convert_case($name, MB_CASE_TITLE, "UTF-8");
    }

    public function scopeNotEmpty($query)
    {
        return $query->join('points', 'points.region_id', '=', 'regions.id')
                     ->leftJoin('users', 'users.id', '=', 'points.user_id')
                     ->select('regions.*')
                     ->where(function ($query) {
                        $query->where('users.is_active', '=', 'true')
                              ->orWhereNull('users.id');
                     })
                     ->groupBy('regions.id', 'regions.name');
    }
}

app/Http/Controllers/Admin/RegionController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

use App\Models\Region as RegionModel;
use App\Models\Country as CountryModel;

class RegionController extends Controller
{
    /**
     * Display a listing of the regions.
     *
     * @return Response
     */
    public function index(RegionModel $regionModel)
    {
        $regions = $regionModel->paginate(20);

        return view('admin.region.index', ['regions' => $regions]);
    }

    /**
     * Show the form for creating a new region.
     *
     * @return Response
     */
    public function create(CountryModel $countryModel)
    {
        $countries = $countryModel->all();

        return view('admin.region.create', ['countries' => $countries]);
    }

    /**
     * Store a newly created region in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request, RegionModel $regionModel)
    {
        $validator = $this->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        $region = $regionModel->create($request->all());

        $process = ['success' => true, 'message' => 'Region created!'];

        return redirect(route('admin.region.show', $region))->with('create', $process);
    }

    /**
     * Display the specified region.
     *
     * @param  App\Models\Region  $region
     * @return Response
     */
    public function show($region)
    {
        return view('admin.region.show', ['region' => $region]);
    }

    /**
     * Show the form for editing the specified region.
     *
     * @param  App\Models\Region  $region
     * @return Response
     */
    public function edit(CountryModel $countryModel, $region)
    {
        $countries = $countryModel->all();

        return view('admin.region.edit', ['region' => $region, 'countries' => $countries]);
    }

    /**
     * Update the specified region in storage.
     *
     * @param  Request  $request
     * @param  App\Models\Region  $region
     * @return Response
     */
    public function update(Request $request, $region)
    {
        $validator = $this->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        $region->fill($request->all());
        $region->save();

        $process = ['success' => true, 'message' => 'Region updated!'];

        return redirect(route('admin.region.edit', $region))->with('update', $process);
    }

    /**
     * Remove the specified region from storage.
     *
     * @param  App\Models\Region  $region
     * @return Response
     */
    public function destroy($region)
    {
        $region->delete();
        $process = ['success' => true, 'message' => 'Region removed!'];

        return redirect()->back()->with('delete', $process);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'country_id' => 'required|exists:countries,id'
        ]);
    }
}

app/Http/Controllers/Main/RegionController.php
<?php

namespace App\Http\Controllers\Main;

use Validator;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Region as RegionModel;

class RegionController extends Controller
{
    protected $regionModel;

    public function __construct(RegionModel $regionModel)
    {
        $this->regionModel = $regionModel;
    }

    /**
     * Listing of the points as json.
     *
     * @return Response
     */
    public function indexJson(Request $request)
    {
        $regions = $this->regionModel->get();
        $activeRegionsIds = array_flatten($this->regionModel->notEmpty()->select(['regions.id'])->get()->toArray());

        foreach ($regions as $region) {
            $region->active = (false !== array_search($region->id, $activeRegionsIds)) ? true : false;
        }

        return response()->json($regions);
    }
}

resources/views/admin/region/create.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Region create')
@section('contentheader_title', 'Region')
@section('contentheader_description', 'create')

@section('breadcrumb')
  @parent
  <li><a href="{{{ route('admin.region.index') }}}">Regions list</a></li>
  <li class="active">Region create</li>
@stop

@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">New region</div>
      <div class="panel-body">
        <div class="box-body no-padding">
          <form autocomplete="off" method="POST" name="create_region" action="{{ route('admin.region.store') }}">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="POST">
            <div class="box-body">
              <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                <label for="name">Name</label>
                <input value="{{ old('name') }}" autocomplete="off" type="text" name="name" class="form-control" id="name" placeholder="Name">
                @if ($errors->has('name'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('name') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('country_id') ? 'has-error' : ''}}">
                <label for="country_id">Country</label>
                <select name="country_id" class="form-control select2" id="country_id">
                  @foreach ($countries as $country)
                      <option {{ old('country_id' == $country->id ? 'selected' : '')}} value="{{ $country->id }}">{{ $country->name }}</option>
                  @endforeach
                </select>
                @if ($errors->has('country_id'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('country_id') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
            </div><!-- /.box-body -->

            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/region/edit.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Region ' . $region->name . ' edit')
@section('contentheader_title', 'Region')
@section('contentheader_description', 'edit')

@section('breadcrumb')
  @parent
  <li><a href="{{{ route('admin.region.index') }}}">Regions list</a></li>
  <li class="active">Region {{ $region->name }} edit </li>
@stop
@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">{{ $region->name }}</div>
      <div class="panel-body">
        <div class="box-body no-padding">
          @if (session('update'))
            <div class="alert alert-success">
                {{ session('update')['message'] }}
            </div>
          @endif
          <form autocomplete="off" method="POST" name="edit_region" action="{{ route('admin.region.update', $region) }}">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="PUT">
            <div class="box-body">
              <div class="box-body">
              <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                <label for="name">Name</label>
                <input value="{{ old('name', $region->name) }}" autocomplete="off" type="text" name="name" class="form-control" id="name" placeholder="Name">
                @if ($errors->has('name'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('name') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('country_id') ? 'has-error' : ''}}">
                <label for="country_id">Country</label>
                <select name="country_id" class="form-control select2" id="country_id">
                  @foreach ($countries as $country)
                      <option {{ old('country_id', $region->country->id) == $country->id ? 'selected' : ''}} value="{{ $country->id }}">{{ $country->name }}</option>
                  @endforeach
                </select>
                @if ($errors->has('country_id'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('country_id') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
            </div><!-- /.box-body -->

            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/region/index.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Regions list')
@section('contentheader_title', 'Regions')
@section('contentheader_description', 'list')

@section('breadcrumb')
  @parent
  <li class="active">Regions list</li>
@stop

@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Regions <a class="btn btn-xs btn-info pull-right" href="{{ route('admin.region.create')}}">Add Region</a></div>

      <div class="panel-body">
        <div class="box-body no-padding">
            @if (session('delete'))
              <div class="alert {{ session('delete')['success'] ? 'alert-success': 'alert-error'}}">
                  {{ session('delete')['message'] }}
              </div>
            @endif
            <table class="table table-hover table-bordered">
              <tbody>
                <tr>
                  <th style="width: 30px">Id</th>
                  <th>Country</th>
                  <th>Name</th>
                  <th style="width: 80px">Created</th>
                  <th style="width: 80px">Actions</th>
                </tr>
                @if (count($regions) > 0)
                  @foreach ($regions as $region)
                  <tr>
                    <td>{{ $region->id }}</td>
                    <td>{{ $region->country->name }}</td>
                    <td>{{ $region->name }}</td>
                    <td>{{ date('d.m.Y', strtotime($region->createdAt)) }}</td>
                    <td>
                      <a href="{{ route('admin.region.show', $region) }}"><i class='fa fa-eye'>&nbsp;</i></a>
                      <a href="{{ route('admin.region.edit', $region) }}"><i class='fa fa-edit'>&nbsp;</i></a>
                      <form id="delete_region_{{$region->id}}" style="display:none" action="{{ route('admin.region.destroy', $region) }}" method="POST">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="_method" value="DELETE">
                      </form>
                      <a href="#" onclick="document.getElementById('delete_region_{{$region->id}}').submit();"><i class='fa fa-trash'>&nbsp;</i></a>
                    </td>
                  </tr>
                  @endforeach
                @else
                  <tr>
                    <td colspan='9'>Nothing here.. But you can <a href="{{ route('admin.region.create')}}">create ;)</a></td>
                  <tr>
                @endif
              </tbody>
            </table>
        </div>

        {!! $regions->render() !!}
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/region/show.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Region ' . $region->name . ' show')
@section('contentheader_title', 'Region')
@section('contentheader_description', $region->name)

@section('breadcrumb')
  @parent
  <li><a href="{{{ route('admin.region.index') }}}">Regions list</a></li>
  <li class="active">Region  {{ $region->name }}</li>
@stop

@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Region {{ $region->name }}
        <a class="btn btn-xs btn-info pull-right" href="{{ route('admin.region.edit', $region) }}">Edit Region</a>
      </div>

      <div class="panel-body">
        <div class="box-body no-padding">
            @if (session('create'))
              <div class="alert alert-success">
                  {{ session('create')['message'] }}
              </div>
            @endif
            <table class="table table-hover table-bordered">
              <tbody>
                  <tr>
                    <th style="width: 60px">Property</th>
                    <th>Value</th>
                  </tr>
                  <tr>
                    <td>ID</td>
                    <td>{{ $region->id }}</td>
                  </tr>
                  <tr>
                    <td>Name</td>
                    <td>{{ $region->name }}</td>
                  </tr>
                  <tr>
                    <td>Country</td>
                    <td>{{ $region->country->name }}</td>
                  </tr>
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection