app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['uses' => 'Main\PageController@main', 'as' => 'home']);


Route::get('/finder/{region?}', ['uses' => 'Main\PageController@finder', 'as' => 'finder'])
        ->where('region', '[0-9]+');

// logout any user
Route::get('auth/logout', ['uses' => 'Auth\AuthController@getLogout', 'as' => 'logout']);

/* USER ROUTES */

// user login page
Route::get('auth/login', ['uses' => 'Auth\AuthController@getLogin', 'as' => 'login']);

// user register page
Route::get('auth/register', ['uses' => 'Auth\AuthController@getRegister', 'as' => 'register.page']);

// user register
Route::post('auth/register', ['uses' => 'Auth\AuthController@postRegister', 'as' => 'register']);

// user register success
Route::get('auth/register/success', ['uses' => 'Auth\AuthController@registerSuccess', 'as' => 'register.success']);

// user login page
Route::post('auth/login', ['uses' => 'Auth\AuthController@postLogin', 'as' => 'auth']);

/* PROFILE ROUTES */

// profile page
Route::get('/profile', ['uses' => 'Main\ProfileController@showProfile', 'as' => 'user.profile', 'middleware' => 'auth']);

// profile update user
Route::post('/profile/update/user', ['uses' => 'Main\ProfileController@updateUser', 'as' => 'profile.update_user', 'middleware' => 'auth']);

// profile update user
Route::post('/profile/update/point', ['uses' => 'Main\ProfileController@updatePoint', 'as' => 'profile.update_point', 'middleware' => 'auth']);

// profile change password
Route::post('/profile/change_password', ['uses' => 'Main\ProfileController@changePassword', 'as' => 'profile.change_password', 'middleware' => 'auth']);

// point show
Route::get('point/{point}/show', ['uses' => 'Main\PointController@show', 'as' => 'point.show'])->where('point', '[0-9]+');

// points list
Route::get('point/{pointsType}/{region?}/', ['uses' => 'Main\PointController@index', 'as' => 'point.index'])
        ->where('pointsType', '[0-9]+')
        ->where('region', '[0-9]+');

// points list json
Route::get('/api/point', ['uses' => 'Main\PointController@indexJson', 'as' => 'point.index_json']);

// regions list json
Route::get('/api/region', ['uses' => 'Main\RegionController@indexJson', 'as' => 'region.index_json']);


/* ADMIN ROUTES */

// admin login page
Route::get('admin/login', ['uses' => 'Auth\AuthController@getAdminLogin', 'as' => 'admin.login']);

// admin auth
Route::post('admin/login', ['uses' => 'Auth\AuthController@postAdminLogin', 'as' => 'admin.auth']);

Route::group(['prefix' => 'admin', 'middleware' => 'auth.admin'], function() {

    Route::get('/', ['uses' => 'Main\PageController@adminDashboard', 'as' => 'admin.home']);

    // admin users CRUD
    Route::resource('user', 'Admin\UserController');
    // admin users other
    Route::post('user/{user}/active', ['uses' => 'Admin\UserController@active', 'as' => 'admin.user.active'])->where('user', '[0-9]+');

    // admin points types CRUD
    Route::resource('pointsType', 'Admin\PointsTypeController');

    // admin country CRUD
    Route::resource('country', 'Admin\CountryController');

    // admin region CRUD
    Route::resource('region', 'Admin\RegionController');

    // admin points CRUD
    Route::resource('point', 'Admin\PointController');

    // subscribe
    Route::get('subscribe', ['uses' => 'Admin\SubscribeController@index', 'as' => 'admin.subscribe']);

    // subscribe
    Route::post('subscribe/store', ['uses' => 'Admin\SubscribeController@store', 'as' => 'admin.subscribe.store']);


    Route::get('subscribe/create', ['uses' => 'Admin\SubscribeController@create', 'as' => 'admin.subscribe.create']);

    /*
    * missing routes of admin group
    */
    Route::any('{_missing}', ['uses' => 'Main\PageController@adminNotFound'])
        ->where('_missing', '.*+');
});

app/Models/Point.php
<?php

namespace App\Models;

use App\Models\Traits\CamelCaseAttributes;
use App\Models\Traits\NullIfEmpty;

use Illuminate\Database\Eloquent\Model;

class Point extends Model
{
    use CamelCaseAttributes, NullIfEmpty;

    public static $snakeAttributes = true;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'points';

    /**
    * Nullable fields auto convert to null if empty
    */
    protected $nullable = ['user_id'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['user_id', 'created_at', 'updated_at', 'airsoftinfo_id'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'address', 'phone', 'description', 'lat', 'lng', 'type_id', 'user_id', 'region_id', 'airsoftinfo_id', 'has_avatar', 'is_vip', 'is_bad'];

    public function type()
    {
        return $this->belongsTo('App\Models\PointsType', 'type_id');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function region()
    {
        return $this->belongsTo('App\Models\Region');
    }

    public function photos()
    {
        return $this->hasMany('App\Models\Photo', 'point_id')->orderBy('id', 'desc');
    }


    public function getHasPhotoAttribute()
    {
      return false;
    }

    public function getAvatarAttribute()
    {
        return '/img/pika.png';
    }

    public function getActiveAttribute()
    {
        $count = $this->leftJoin('users', 'users.id', '=', 'points.user_id')
                    ->select('points.*')
                    ->where('points.id', '=', $this->id)
                    ->where(function ($query) {
                        $query->where('users.is_active', '=', 'true')
                              ->orWhereNull('users.id');
                    })
                    ->count();

        return $count > 0;
    }

    public function scopeActive($query)
    {
        return $query->leftJoin('users', 'users.id', '=', 'points.user_id')
                     ->select('points.*')
                     ->where(function ($query) {
                        $query->where('users.is_active', '=', 'true')
                              ->orWhereNull('users.id');
                     });
    }

    public function scopeOfType($query, \App\Models\pointsType $pointsType = null)
    {
        if (!empty($pointsType)) {
            $query = $query->whereTypeId($pointsType->id);
        }

        return $query;
    }

    public function scopeInTypes($query, array $pointsTypes = null)
    {
        if (!empty($pointsTypes)) {
            $query = $query->whereIn('type_id', $pointsTypes);
        }

        return $query;
    }

    public function scopeOfRegion($query, \App\Models\Region $region = null)
    {
        if (!empty($region)) {
            $query = $query->whereRegionId($region->id);
        }

        return $query;
    }
}

app/Models/PointsType.php
<?php

namespace App\Models;

use App\Models\Traits\CamelCaseAttributes;
use Illuminate\Database\Eloquent\Model;

use App\Models\Region as RegionModel;

class PointsType extends Model
{
    use CamelCaseAttributes;

    public static $snakeAttributes = true;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'points_types';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'description'];

    public function points()
    {
        return $this->hasMany('App\Models\Point', 'type_id')->orderBy('name', 'desc');
    }

    public function getRegionsAttribute()
    {
        return RegionModel::join('points', 'points.region_id', '=', 'regions.id')
                          ->join('points_types', 'points.type_id', '=', 'points_types.id')
                          ->leftJoin('users', 'points.user_id', '=', 'users.id')
                          ->select('regions.id', 'regions.name')
                          ->where('points_types.id', '=', $this->id)
                          ->where(function ($query) {
                              $query->where('users.is_active', '=', 'true')
                                    ->orWhereNull('users.id');
                              })
                          ->groupBy('regions.id', 'regions.name')
                          ->get();
    }

    public function getIconAttribute()
    {
      return '/img/icons/menu/field.svg';
    }

    public function scopeNotEmpty($query)
    {
        return $query->join('points', 'points.type_id', '=', 'points_types.id')
                     ->leftJoin('users', 'users.id', '=', 'points.user_id')
                     ->select('points_types.*')
                     ->where(function ($query) {
                        $query->where('users.is_active', '=', 'true')
                              ->orWhereNull('users.id');
                     })
                     ->groupBy('points_types.id', 'points_types.name');
    }
}

app/Http/Controllers/Admin/PointController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

use App\Models\Point as PointModel;
use App\Models\User as UserModel;
use App\Models\PointsType as PointsTypeModel;
use App\Models\Region as RegionModel;

class PointController extends Controller
{
    /**
     * Display a listing of the points.
     *
     * @return Response
     */
    public function index(PointModel $pointModel)
    {
        $points = $pointModel->paginate(20);

        return view('admin.point.index', ['points' => $points]);
    }

    /**
     * Show the form for creating a new point.
     *
     * @return Response
     */
    public function create(PointsTypeModel $pointsTypeModel, UserModel $userModel, RegionModel $regionModel)
    {
        $pointsTypes = $pointsTypeModel->all();
        $regions = $regionModel->all();

        $users = $userModel->leftJoin('points', 'points.user_id', '=', 'users.id')
                            ->whereNull('points.user_id')
                            ->select('users.id', 'users.email')
                            ->get();

        return view('admin.point.create', ['pointsTypes' => $pointsTypes, 'users' => $users, 'regions' => $regions]);
    }

    /**
     * Store a newly created point in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request, PointModel $pointModel)
    {
        $validator = $this->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        $point = $pointModel->create($request->all());

        $process = ['success' => true, 'message' => 'Point created!'];

        return redirect(route('admin.point.show', $point))->with('create', $process);
    }

    /**
     * Display the specified point.
     *
     * @param  App\Models\Point  $point
     * @return Response
     */
    public function show($point)
    {
        return view('admin.point.show', ['point' => $point]);
    }

    /**
     * Show the form for editing the specified point.
     *
     * @param  App\Models\Point  $point
     * @return Response
     */
    public function edit(PointsTypeModel $pointsTypeModel, UserModel $userModel, RegionModel $regionModel, $point)
    {
        $pointsTypes = $pointsTypeModel->all();
        $regions = $regionModel->all();

        $users = $userModel->leftJoin('points', 'points.user_id', '=', 'users.id')
                            ->whereNull('points.user_id')
                            ->orWhere('points.id', $point->id)
                            ->select('users.id', 'users.email')
                            ->get();

        return view('admin.point.edit', ['point' => $point, 'pointsTypes' => $pointsTypes, 'users' => $users, 'regions' => $regions]);
    }

    /**
     * Update the specified point in storage.
     *
     * @param  Request  $request
     * @param  App\Models\Point  $point
     * @return Response
     */
    public function update(Request $request, $point)
    {
        if ($request->has('user_id') && $request->get('user_id') == $point->userId)
            $request->offsetUnset('user_id');

        $validator = $this->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        $point->fill($request->all());
        $point->save();

        $process = ['success' => true, 'message' => 'Point updated!'];

        return redirect(route('admin.point.edit', $point))->with('update', $process);
    }

    /**
     * Remove the specified point from storage.
     *
     * @param  App\Models\Point  $point
     * @return Response
     */
    public function destroy($point)
    {
        $point->delete();
        $process = ['success' => true, 'message' => 'Point removed!'];

        return redirect()->back()->with('delete', $process);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'type_id' => 'required|exists:points_types,id',
            'region_id' => 'required|exists:regions,id',
            'user_id' => 'sometimes|exists:users,id|unique:points',
            'lat' => 'required|numeric',
            'lng' => 'required|numeric'
        ]);
    }
}

app/Http/Controllers/Main/PointController.php
<?php

namespace App\Http\Controllers\Main;

use Validator;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Point as PointModel;
use App\Models\PointsType as PointsTypeModel;
use App\Models\Country as CountryModel;
use App\Models\Region as RegionModel;

class PointController extends Controller
{
    protected $pointsTypeModel;
    protected $pointModel;
    protected $countryModel;
    protected $regionModel;

    public function __construct(PointModel $pointModel, PointsTypeModel $pointsTypeModel, CountryModel $countryModel, RegionModel $regionModel)
    {
        $this->pointsTypeModel = $pointsTypeModel;
        $this->pointModel = $pointModel;
        $this->countryModel = $countryModel;
        $this->regionModel = $regionModel;
    }

    /**
     * Display a listing of the points.
     *
     * @return Response
     */
    public function index($pointsType, $region = null)
    {
        $pointsCount = $this->pointModel->active()->ofType($pointsType)->ofRegion($region)->count();

        if ($pointsCount === 0)
            \App::abort(404);

        return view('main.point.index', ['pointsCount' => $pointsCount, 'pointsType' => $pointsType, 'region' => $region]);
    }

    /**
     * Display the specified point.
     *
     * @param  App\Models\Point  $point
     * @return Response
     */
    public function show($point)
    {
        if (!$point->active)
            \App::abort(404);

        return view('main.point.show', ['point' => $point]);
    }

    /**
     * Listing of the points as json.
     *
     * @return Response
     */
    public function indexJson(Request $request)
    {
        $validator = $this->validator($request->all());

        if (!$validator->fails()) {
            $pointsTypes = $request->get('type');
            $region = $request->get('region');
            $points = $this->pointModel->active()
                                        ->inTypes($pointsTypes)
                                        ->ofRegion($this->regionModel->whereId($region)->first())
                                        ->with('type', 'region')
                                        ->get();

        } else {
            $points = [];
        }

        return response()->json($points);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'type' => 'sometimes|required|arrayWithNums|exists:points_types,id',
            'region' => 'sometimes|required|numeric|exists:regions,id'
        ]);
    }
}

resources/views/admin/point/create.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Point create')
@section('contentheader_title', 'Point')
@section('contentheader_description', 'create')

@section('breadcrumb')
  @parent
  <li><a href="{{{ route('admin.point.index') }}}">Points list</a></li>
  <li class="active">Point create</li>
@stop

@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">New point</div>
      <div class="panel-body">
        <div class="box-body no-padding">
          <form autocomplete="off" method="POST" name="create_point" action="{{ route('admin.point.store') }}">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="POST">
            <input type="checkbox" {{ old('map_opened') ? 'checked' : ''}} name="map_opened" class="j-internal_map_opened" type="checkbox" style="display: none">
            <div class="box-body">
              <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                <label for="name">Name</label>
                <input value="{{ old('name') }}" autocomplete="off" type="text" name="name" class="form-control" id="name" placeholder="Name">
                @if ($errors->has('name'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('name') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('phone') ? 'has-error' : ''}}">
                <label for="phone">Phone</label>
                <input value="{{ old('phone') }}" autocomplete="off" type="text" name="phone" class="form-control" id="phone" placeholder="+7 (999) 999-9999">
                @if ($errors->has('phone'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('phone') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('region_id') ? 'has-error' : ''}}">
                <label for="region_id">Region</label>
                <select name="region_id" class="form-control select2" id="region_id">

                  @foreach ($regions as $region)
                      <option {{ old('region_id') == $region->id ? 'selected' : ''}} value="{{ $region->id }}">{{ $region->name }}</option>
                  @endforeach
                </select>
                @if ($errors->has('region_id'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('region_id') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('address') ? 'has-error' : ''}}">
                <label for="address">Address</label>
                <input value="{{ old('address') }}" autocomplete="off" type="text" name="address" class="form-control" id="address" placeholder="Address">
                @if ($errors->has('address'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('address') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('lat') ? 'has-error' : ''}}">
                <label for="lat">Lat</label>
                <input value="{{ old('lat') }}" autocomplete="off" type="text" name="lat" class="form-control" id="lat" placeholder="55.7522200">
                @if ($errors->has('lat'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('lat') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('lng') ? 'has-error' : ''}}">
                <label for="lng">Lng</label>
                <input value="{{ old('lng') }}" autocomplete="off" type="text" name="lng" class="form-control" id="lng" placeholder="37.6155600">
                @if ($errors->has('lng'))
                  <div class="alert-danger">
                    <ul>
                      @foreach ($errors->get('lng') as $error)
                          <li>{{ $error }}</li>
                      @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="box box-default {{ old('map_opened') ? '' : 'collapsed-box' }}">
                <div class="box-header with-border">
                  <h3 class="box-title">map</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool j-internal_map" data-widget="collapse"><i class="fa fa-{{ old('map_opened') ? 'minus' : 'plus' }}">.</i></button>
                  </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body" style="display: {{ old('map_opened') ? 'block' : 'none' }};">
                  <div id="g-map"style="height: 400px"></div>
                </div>
              </div>
              <div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
                <label for="description">Description</label>
                <textarea name="description" class="form-control textarea-wysilhtml" id="description" placeholder="Description">{{ old('description') }}</textarea>
                @if ($errors->has('description'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('description') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('type_id') ? 'has-error' : ''}}">
                <label for="type_id">Type</label>
                <select name="type_id" class="form-control select2" id="type_id">
                  @foreach ($pointsTypes as $pointsType)
                      <option {{ old('type_id') == $pointsType->id ? 'selected' : ''}} value="{{ $pointsType->id }}">{{ $pointsType->name }}</option>
                  @endforeach
                </select>
                @if ($errors->has('type_id'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('type_id') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('user_id') ? 'has-error' : ''}}">
                <label for="user_id">User</label>
                <select name="user_id" class="form-control select2" id="user_id">
                  <option value="">&mdash;</option>
                  @foreach ($users as $user)
                      <option {{ old('user_id') == $user->id ? 'selected' : ''}} value="{{ $user->id }}">{{ $user->email }}</option>
                  @endforeach
                </select>
                @if ($errors->has('user_id'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('user_id') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="checkbox">
                <label>
                  <input {{ old('is_vip') ? 'checked' : ''}} type="checkbox" name="is_vip"> VIP
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input {{ old('is_bad') ? 'checked' : ''}} type="checkbox" name="is_bad"> Залет
                </label>
              </div>
            </div><!-- /.box-body -->
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/point/index.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Points list')
@section('contentheader_title', 'Points')
@section('contentheader_description', 'list')

@section('breadcrumb')
  @parent
  <li class="active">Points list</li>
@stop

@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Points <a class="btn btn-xs btn-info pull-right" href="{{ route('admin.point.create')}}">Add Point</a></div>

      <div class="panel-body">
        <div class="box-body no-padding">
            @if (session('delete'))
              <div class="alert {{ session('delete')['success'] ? 'alert-success': 'alert-error'}}">
                  {{ session('delete')['message'] }}
              </div>
            @endif
            <table class="table table-hover table-bordered">
              <tbody>
                <tr>
                  <th style="width: 30px">Id</th>
                  <th>Name</th>
                  <th>Phone</th>
                  <th style="width: 80px">Address</th>
                  <th style="width: 20px">Lat</th>
                  <th style="width: 20px">Lng</th>
                  <th style="width: 80px">Type</th>
                  <th style="width: 80px">Created</th>
                  <th style="width: 80px">Actions</th>
                </tr>
                @if (count($points) > 0)
                  @foreach ($points as $point)
                  <tr>
                    <td>{{ $point->id }}</td>
                    <td>{{ $point->name }}</td>
                    <td>{{ $point->phone }}</td>
                    <td>{{ $point->address }}</td>
                    <td>{{ $point->lat }}</td>
                    <td>{{ $point->lng }}</td>
                    <td>{{ $point->type->name }}</td>
                    <td>{{ date('d.m.Y', strtotime($point->createdAt)) }}</td>
                    <td>
                      <a href="{{ route('admin.point.show', $point) }}"><i class='fa fa-eye'>&nbsp;</i></a>
                      <a href="{{ route('admin.point.edit', $point) }}"><i class='fa fa-edit'>&nbsp;</i></a>
                      <form id="delete_point_{{$point->id}}" style="display:none" action="{{ route('admin.point.destroy', $point) }}" method="POST">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="_method" value="DELETE">
                      </form>
                      <a href="#" onclick="document.getElementById('delete_point_{{$point->id}}').submit();"><i class='fa fa-trash'>&nbsp;</i></a>
                    </td>
                  </tr>
                  @endforeach
                @else
                  <tr>
                    <td colspan='9'>Nothing here.. But you can <a href="{{ route('admin.point.create')}}">create ;)</a></td>
                  <tr>
                @endif
              </tbody>
            </table>
        </div>

        {!! $points->render() !!}
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/point/show.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Point ' . $point->name . ' show')
@section('contentheader_title', 'Point')
@section('contentheader_description', $point->name)

@section('breadcrumb')
  @parent
  <li><a href="{{{ route('admin.point.index') }}}">Points list</a></li>
  <li class="active">Point  {{ $point->name }}</li>
@stop

@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Point {{ $point->name }}
        <a class="btn btn-xs btn-info pull-right" href="{{ route('admin.point.edit', $point) }}">Edit Point</a>
      </div>

      <div class="panel-body">
        <div class="box-body no-padding">
            @if (session('create'))
              <div class="alert alert-success">
                  {{ session('create')['message'] }}
              </div>
            @endif
            <table class="table table-hover table-bordered">
              <tbody>
                  <tr>
                    <th style="width: 60px">Property</th>
                    <th>Value</th>
                  </tr>
                  <tr>
                    <td>ID</td>
                    <td>{{ $point->id }}</td>
                  </tr>
                  <tr>
                    <td>Name</td>
                    <td>{{ $point->name }}</td>
                  </tr>
                  <tr>
                    <td>Phone</td>
                    <td>{{ $point->phone }}</td>
                  </tr>
                  <tr>
                    <td>Adsress</td>
                    <td>{{ $point->address }}</td>
                  </tr>
                  <tr>
                    <td>Description</td>
                    <td>{{ $point->description }}</td>
                  </tr>
                  <tr>
                    <td>lat</td>
                    <td>{{ $point->lat }}</td>
                  </tr>
                  <tr>
                    <td>lng</td>
                    <td>{{ $point->lng }}</td>
                  </tr>
                  <tr>
                    <td>Type</td>
                    <td>{{ $point->type->name }}</td>
                  </tr>
                  <tr>
                    <td>VIP</td>
                    <td><span class="label label-{{ $point->is_vip ? 'success' : 'warning' }}">{{ $point->is_vip ? 'Yes' : 'No' }}</span></td>
                  </tr>
                  <tr>
                    <td>Залет</td>
                    <td><span class="label label-{{ $point->is_bad ? 'success' : 'warning' }}">{{ $point->is_bad ? 'Yes' : 'No' }}</span></td>
                  </tr>
                  <tr>
                    <td>User</td>
                    <td>
                      @if ($point->user)
                        <a href="{{ route('admin.user.show', $point->user) }}">{{ $point->user->email }}</a>
                      @else
                        &mdash;
                      @endif
                    </td>
                  </tr>
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection