app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['uses' => 'Main\PageController@main', 'as' => 'home']);


Route::get('/finder/{region?}', ['uses' => 'Main\PageController@finder', 'as' => 'finder'])
        ->where('region', '[0-9]+');

// logout any user
Route::get('auth/logout', ['uses' => 'Auth\AuthController@getLogout', 'as' => 'logout']);

/* USER ROUTES */

// user login page
Route::get('auth/login', ['uses' => 'Auth\AuthController@getLogin', 'as' => 'login']);

// user register page
Route::get('auth/register', ['uses' => 'Auth\AuthController@getRegister', 'as' => 'register.page']);

// user register
Route::post('auth/register', ['uses' => 'Auth\AuthController@postRegister', 'as' => 'register']);

// user register success
Route::get('auth/register/success', ['uses' => 'Auth\AuthController@registerSuccess', 'as' => 'register.success']);

// user login page
Route::post('auth/login', ['uses' => 'Auth\AuthController@postLogin', 'as' => 'auth']);

/* PROFILE ROUTES */

// profile page
Route::get('/profile', ['uses' => 'Main\ProfileController@showProfile', 'as' => 'user.profile', 'middleware' => 'auth']);

// profile update user
Route::post('/profile/update/user', ['uses' => 'Main\ProfileController@updateUser', 'as' => 'profile.update_user', 'middleware' => 'auth']);

// profile update user
Route::post('/profile/update/point', ['uses' => 'Main\ProfileController@updatePoint', 'as' => 'profile.update_point', 'middleware' => 'auth']);

// profile change password
Route::post('/profile/change_password', ['uses' => 'Main\ProfileController@changePassword', 'as' => 'profile.change_password', 'middleware' => 'auth']);

// point show
Route::get('point/{point}/show', ['uses' => 'Main\PointController@show', 'as' => 'point.show'])->where('point', '[0-9]+');

// points list
Route::get('point/{pointsType}/{region?}/', ['uses' => 'Main\PointController@index', 'as' => 'point.index'])
        ->where('pointsType', '[0-9]+')
        ->where('region', '[0-9]+');

// points list json
Route::get('/api/point', ['uses' => 'Main\PointController@indexJson', 'as' => 'point.index_json']);

// regions list json
Route::get('/api/region', ['uses' => 'Main\RegionController@indexJson', 'as' => 'region.index_json']);


/* ADMIN ROUTES */

// admin login page
Route::get('admin/login', ['uses' => 'Auth\AuthController@getAdminLogin', 'as' => 'admin.login']);

// admin auth
Route::post('admin/login', ['uses' => 'Auth\AuthController@postAdminLogin', 'as' => 'admin.auth']);

Route::group(['prefix' => 'admin', 'middleware' => 'auth.admin'], function() {

    Route::get('/', ['uses' => 'Main\PageController@adminDashboard', 'as' => 'admin.home']);

    // admin users CRUD
    Route::resource('user', 'Admin\UserController');
    // admin users other
    Route::post('user/{user}/active', ['uses' => 'Admin\UserController@active', 'as' => 'admin.user.active'])->where('user', '[0-9]+');

    // admin points types CRUD
    Route::resource('pointsType', 'Admin\PointsTypeController');

    // admin country CRUD
    Route::resource('country', 'Admin\CountryController');

    // admin region CRUD
    Route::resource('region', 'Admin\RegionController');

    // admin points CRUD
    Route::resource('point', 'Admin\PointController');

    // subscribe
    Route::get('subscribe', ['uses' => 'Admin\SubscribeController@index', 'as' => 'admin.subscribe']);

    // subscribe
    Route::post('subscribe/store', ['uses' => 'Admin\SubscribeController@store', 'as' => 'admin.subscribe.store']);


    Route::get('subscribe/create', ['uses' => 'Admin\SubscribeController@create', 'as' => 'admin.subscribe.create']);

    /*
    * missing routes of admin group
    */
    Route::any('{_missing}', ['uses' => 'Main\PageController@adminNotFound'])
        ->where('_missing', '.*+');
});

app/Http/Controllers/Admin/PointsTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

use App\Models\PointsType as PointsTypeModel;

class PointsTypeController extends Controller
{
    /**
     * Display a listing of the points types.
     *
     * @return Response
     */
    public function index(PointsTypeModel $pointsTypeModel)
    {
        $pointsTypes = $pointsTypeModel->paginate(20);

        return view('admin.pointstype.index', ['pointsTypes' => $pointsTypes]);
    }

    /**
     * Show the form for creating a new points type.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.pointstype.create');
    }

    /**
     * Store a newly created points type in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $validator = $this->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        $pointsType = PointsTypeModel::create($request->all());

        $process = ['success' => true, 'message' => 'Points type created!'];

        return redirect(route('admin.pointsType.show', $pointsType))->with('create', $process);
    }

    /**
     * Display the specified points type.
     *
     * @param  App\Models\PointsType  $pointsType
     * @return Response
     */
    public function show($pointsType)
    {
        return view('admin.pointstype.show', ['pointsType' => $pointsType]);
    }

    /**
     * Show the form for editing the specified points type.
     *
     * @param  App\Models\PointsType  $pointsType
     * @return Response
     */
    public function edit($pointsType)
    {
        return view('admin.pointstype.edit', ['pointsType' => $pointsType]);
    }

    /**
     * Update the specified points type in storage.
     *
     * @param  Request  $request
     * @param  App\Models\PointsType  $pointsType
     * @return Response
     */
    public function update(Request $request, $pointsType)
    {
        if ($request->has('name') && $request->get('name') === $pointsType->name)
            $request->offsetUnset('name');

        $validator = $this->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        $pointsType->fill($request->all());
        $pointsType->save();

        $process = ['success' => true, 'message' => 'Points type updated!'];

        return redirect(route('admin.pointsType.edit', $pointsType))->with('update', $process);
    }

    /**
     * Remove the specified points type from storage.
     *
     * @param  App\Models\PointsType  $pointsType
     * @return Response
     */
    public function destroy($pointsType)
    {
        $pointsType->delete();
        $process = ['success' => true, 'message' => 'Points type removed!'];

        return redirect()->back()->with('delete', $process);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'sometimes|unique:points_types|required|max:255'
        ]);
    }
}

resources/views/admin/pointstype/create.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Points type create')
@section('contentheader_title', 'Points type')
@section('contentheader_description', 'create')

@section('breadcrumb')
  @parent
  <li><a href="{{{ route('admin.pointsType.index') }}}">Points types list</a></li>
  <li class="active">Points Type create</li>
@stop

@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">New points type</div>
      <div class="panel-body">
        <div class="box-body no-padding">
          <form autocomplete="off" method="POST" name="create_points_type" action="{{ route('admin.pointsType.store') }}">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="POST">

            <div class="box-body">
              <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                <label for="name">Name</label>
                <input value="{{ old('name') }}" autocomplete="off" type="text" name="name" class="form-control" id="name" placeholder="Name">
                @if ($errors->has('name'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('name') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
                <label for="description">Description</label>
                <textarea name="description" class="form-control textarea-wysilhtml" id="description" placeholder="description">{{ old('description') }}</textarea>
                @if ($errors->has('description'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('description') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
            </div><!-- /.box-body -->

            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/pointstype/edit.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Points type ' .  $pointsType->name  . ' edit')
@section('contentheader_title', 'Points type')
@section('contentheader_description', 'edit')

@section('breadcrumb')
  @parent
  <li><a href="{{{ route('admin.pointsType.index') }}}">Points types list</a></li>
  <li class="active">Points type {{ $pointsType->name }} edit </li>
@stop

@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">{{ $pointsType->name }}</div>
      <div class="panel-body">
        <div class="box-body no-padding">
          @if (session('update'))
            <div class="alert alert-success">
                {{ session('update')['message'] }}
            </div>
          @endif
          <form autocomplete="off" method="POST" name="create_points_type" action="{{ route('admin.pointsType.update', $pointsType) }}">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="PUT">
            <div class="box-body">
              <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                <label for="name">Name</label>
                <input value="{{ old('name', $pointsType->name) }}" autocomplete="off" type="text" name="name" class="form-control" id="name" placeholder="Name">
                @if ($errors->has('name'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('name') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
                <label for="description">Description</label>
                <textarea name="description" class="form-control textarea-wysilhtml" id="description" placeholder="Description">{{ old('description', $pointsType->description) }}</textarea>
                @if ($errors->has('description'))
                  <div class="alert-danger">
                    <ul>
                  @foreach ($errors->get('description') as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                    </ul>
                  </div>
                @endif
              </div>
            </div><!-- /.box-body -->

            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/pointstype/index.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Points types list')
@section('contentheader_title', 'Points types')
@section('contentheader_description', 'list')

@section('breadcrumb')
  @parent
  <li class="active">Points types list</li>
@stop

@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Points types <a class="btn btn-xs btn-info pull-right" href="{{ route('admin.pointsType.create')}}">Add Points Type</a></div>

      <div class="panel-body">
        <div class="box-body no-padding">
            @if (session('delete'))
              <div class="alert {{ session('delete')['success'] ? 'alert-success': 'alert-error'}}">
                  {{ session('delete')['message'] }}
              </div>
            @endif
            <table class="table table-hover table-bordered">
              <tbody>
                <tr>
                  <th style="width: 30px">Id</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th style="width: 80px">Created</th>
                  <th style="width: 80px">Actions</th>
                </tr>
                @if (count($pointsTypes) > 0)
                  @foreach ($pointsTypes as $pointsType)
                  <tr>
                    <td>{{ $pointsType->id }}</td>
                    <td>{{ $pointsType->name }}</td>
                    <td>{{ $pointsType->description }}</td>
                    <td>{{ date('d.m.Y', strtotime($pointsType->createdAt)) }}</td>
                    <td>
                      <a href="{{ route('admin.pointsType.show', $pointsType) }}"><i class='fa fa-eye'>&nbsp;</i></a>
                      <a href="{{ route('admin.pointsType.edit', $pointsType) }}"><i class='fa fa-edit'>&nbsp;</i></a>
                      <form id="delete_pointsType_{{$pointsType->id}}" style="display:none" action="{{ route('admin.pointsType.destroy', $pointsType) }}" method="POST">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="_method" value="DELETE">
                      </form>
                      <a href="#" onclick="document.getElementById('delete_pointsType_{{$pointsType->id}}').submit();"><i class='fa fa-trash'>&nbsp;</i></a>
                    </td>
                  </tr>
                  @endforeach
                @else
                  <tr>
                    <td colspan='6'>Nothing here.. But you can <a href="{{ route('admin.pointsType.create')}}">create ;)</a></td>
                  <tr>
                @endif
              </tbody>
            </table>
        </div>

        {!! $pointsTypes->render() !!}
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/pointstype/show.blade.php
@extends('admin.layout')

@section('htmlheader_title', 'Points Type ' .  $pointsType->name . ' show')
@section('contentheader_title', 'Points Type')
@section('contentheader_description', 'show')

@section('breadcrumb')
  @parent
  <li><a href="{{{ route('admin.pointsType.index') }}}">Points types list</a></li>
  <li class="active">Points type {{ $pointsType->name }}</li>
@stop

@section('main-content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">{{ $pointsType->name }}
        <a class="btn btn-xs btn-info pull-right" href="{{ route('admin.pointsType.edit', $pointsType) }}">Edit Points Type</a>
      </div>

      <div class="panel-body">
        <div class="box-body no-padding">
            @if (session('create'))
              <div class="alert alert-success">
                  {{ session('create')['message'] }}
              </div>
            @endif
            <table class="table table-hover table-bordered">
              <tbody>
                  <tr>
                    <th style="width: 60px">Property</th>
                    <th>Value</th>
                  </tr>
                  <tr>
                    <td>ID</td>
                    <td>{{ $pointsType->id }}</td>
                  </tr>
                  <tr>
                    <td>Name</td>
                    <td>{{ $pointsType->name }}</td>
                  </tr>
                  <tr>
                    <td>Description</td>
                    <td>{{ $pointsType->description }}</td>
                  </tr>
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection