app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['uses' => 'Main\PageController@main', 'as' => 'home']);


Route::get('/finder/{region?}', ['uses' => 'Main\PageController@finder', 'as' => 'finder'])
        ->where('region', '[0-9]+');

// logout any user
Route::get('auth/logout', ['uses' => 'Auth\AuthController@getLogout', 'as' => 'logout']);

/* USER ROUTES */

// user login page
Route::get('auth/login', ['uses' => 'Auth\AuthController@getLogin', 'as' => 'login']);

// user register page
Route::get('auth/register', ['uses' => 'Auth\AuthController@getRegister', 'as' => 'register.page']);

// user register
Route::post('auth/register', ['uses' => 'Auth\AuthController@postRegister', 'as' => 'register']);

// user register success
Route::get('auth/register/success', ['uses' => 'Auth\AuthController@registerSuccess', 'as' => 'register.success']);

// user login page
Route::post('auth/login', ['uses' => 'Auth\AuthController@postLogin', 'as' => 'auth']);

/* PROFILE ROUTES */

// profile page
Route::get('/profile', ['uses' => 'Main\ProfileController@showProfile', 'as' => 'user.profile', 'middleware' => 'auth']);

// profile update user
Route::post('/profile/update/user', ['uses' => 'Main\ProfileController@updateUser', 'as' => 'profile.update_user', 'middleware' => 'auth']);

// profile update user
Route::post('/profile/update/point', ['uses' => 'Main\ProfileController@updatePoint', 'as' => 'profile.update_point', 'middleware' => 'auth']);

// profile change password
Route::post('/profile/change_password', ['uses' => 'Main\ProfileController@changePassword', 'as' => 'profile.change_password', 'middleware' => 'auth']);

// point show
Route::get('point/{point}/show', ['uses' => 'Main\PointController@show', 'as' => 'point.show'])->where('point', '[0-9]+');

// points list
Route::get('point/{pointsType}/{region?}/', ['uses' => 'Main\PointController@index', 'as' => 'point.index'])
        ->where('pointsType', '[0-9]+')
        ->where('region', '[0-9]+');

// points list json
Route::get('/api/point', ['uses' => 'Main\PointController@indexJson', 'as' => 'point.index_json']);

// regions list json
Route::get('/api/region', ['uses' => 'Main\RegionController@indexJson', 'as' => 'region.index_json']);


/* ADMIN ROUTES */

// admin login page
Route::get('admin/login', ['uses' => 'Auth\AuthController@getAdminLogin', 'as' => 'admin.login']);

// admin auth
Route::post('admin/login', ['uses' => 'Auth\AuthController@postAdminLogin', 'as' => 'admin.auth']);

Route::group(['prefix' => 'admin', 'middleware' => 'auth.admin'], function() {

    Route::get('/', ['uses' => 'Main\PageController@adminDashboard', 'as' => 'admin.home']);

    // admin users CRUD
    Route::resource('user', 'Admin\UserController');
    // admin users other
    Route::post('user/{user}/active', ['uses' => 'Admin\UserController@active', 'as' => 'admin.user.active'])->where('user', '[0-9]+');

    // admin points types CRUD
    Route::resource('pointsType', 'Admin\PointsTypeController');

    // admin country CRUD
    Route::resource('country', 'Admin\CountryController');

    // admin region CRUD
    Route::resource('region', 'Admin\RegionController');

    // admin points CRUD
    Route::resource('point', 'Admin\PointController');

    // subscribe
    Route::get('subscribe', ['uses' => 'Admin\SubscribeController@index', 'as' => 'admin.subscribe']);

    // subscribe
    Route::post('subscribe/store', ['uses' => 'Admin\SubscribeController@store', 'as' => 'admin.subscribe.store']);


    Route::get('subscribe/create', ['uses' => 'Admin\SubscribeController@create', 'as' => 'admin.subscribe.create']);

    /*
    * missing routes of admin group
    */
    Route::any('{_missing}', ['uses' => 'Main\PageController@adminNotFound'])
        ->where('_missing', '.*+');
});

resources/views/admin/partials/contentheader.blade.php
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        @yield('contentheader_title', 'Page Header here')
        <small>@yield('contentheader_description')</small>
    </h1>
    <ol class="breadcrumb">
        @section('breadcrumb')
        <li><a href="{{{ route('admin.home') }}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        @show
    </ol>
</section>

resources/views/admin/partials/controlsidebar.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        {{--<li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>--}}
        <li class="active"><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        {{--
        <!-- Home tab content -->
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul><!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul><!-- /.control-sidebar-menu -->

        </div><!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane active" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->--}}
        <!-- Settings tab content -->
        <div class="tab-pane active" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked />
                    </label>
                    <p>
                        Some information about this general settings option
                    </p>
                </div><!-- /.form-group -->
            </form>
        </div><!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->

<!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

resources/views/admin/partials/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        {{--<a href="https://github.com/acacha/adminlte-laravel"></a><b>THE DO 2.0.</b></a>. A Laravel 5 package that switchs default Laravel scaffolding/boilerplate to AdminLTE template--}}
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2015 The DO 2.0</strong> Created by finkel
</footer>

resources/views/admin/partials/htmlheader.blade.php
<head>
    <meta charset="UTF-8">
    <title> The DO 2.0 with Laravel - @yield('htmlheader_title', 'Your title here') </title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- select2 -->
    <link href="{{ asset('/plugins/select2/select2.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Bootstrap 3.3.4 -->
    <link href="{{ asset('/css/bootstrap.css') }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ asset('/css/AdminLTE.css') }}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link href="{{ asset('/css/skins/skin-blue.css') }}" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="{{ asset('/plugins/icheck/square/blue.css') }}" rel="stylesheet" type="text/css" />

    <link href="{{ asset('/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

resources/views/admin/partials/mainheader.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{{ route('admin.home') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>T</b>DO</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>The</b>DO 2.0 </span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {{--<!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <!-- inner menu: contains the messages -->
                            <ul class="menu">
                                <li><!-- start message -->
                                    <a href="#">
                                        <div class="pull-left">
                                            <!-- User Image -->
                                            <img src="/img/user2-160x160.jpg" class="img-circle" alt="User Image"/>
                                        </div>
                                        <!-- Message title and timestamp -->
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <!-- The message -->
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li><!-- end message -->
                            </ul><!-- /.menu -->
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li><!-- /.messages-menu -->--}}

                <!-- Notifications Menu -->
                <li class="dropdown notifications-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        @if ($totalNotifications > 0)
                            <span class="label label-warning">{{ $totalNotifications }}</span>
                        @endif
                    </a>
                    <ul class="dropdown-menu">
                        @if ($totalNotifications > 0)
                            <li class="header">You have {{ $totalNotifications }} notifications</li>
                        @else
                            <li class="header">Nothing here</li>
                        @endif
                        <li>
                            <!-- Inner Menu: contains the notifications -->
                            <ul class="menu">
                                <li><!-- start notification -->
                                    @if ($notCheckedUsers > 0)
                                        <a href="{{ route('admin.user.index') }}">
                                            <i class="fa fa-users text-aqua"></i> {{ $notCheckedUsers }} register confirmation.
                                        </a>
                                    @endif
                                </li><!-- end notification -->
                            </ul>
                        </li>
                        {{-- <li class="footer"><a href="#">View all</a></li> --}}
                    </ul>
                </li>
                {{--<!-- Tasks Menu -->
                <li class="dropdown tasks-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <!-- Inner menu: contains the tasks -->
                            <ul class="menu">
                                <li><!-- Task item -->
                                    <a href="#">
                                        <!-- Task title and progress text -->
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <!-- The progress bar -->
                                        <div class="progress xs">
                                            <!-- Change the css width attribute to simulate progress -->
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li><!-- end task item -->
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">View all tasks</a>
                        </li>
                    </ul>
                </li>--}}
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ Auth::user()->hasAvatar ? '/img/uavatars/u_' . Auth::user()->id . '.png' : '/img/blank_avatar.png'}}" class="user-image" alt="User Image"/>
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ Auth::user()->hasAvatar ? '/img/uavatars/u_' . Auth::user()->id . '.png' : '/img/blank_avatar.png'}}" class="img-circle" alt="User Image" />
                            <p>
                                {{ Auth::user()->name }}
                                <small>Member since {{ date('F d, Y', strtotime(Auth::user()->createdAt)) }}</small>
                            </p>
                        </li>
                        {{--<!-- Menu Body -->
                        <li class="user-body">
                            <div class="col-xs-4 text-center">
                                <a href="#">Followers</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Sales</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Friends</a>
                            </div>
                        </li>--}}
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('admin.user.show', Auth::user()) }}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ url('/auth/logout') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/partials/scripts.blade.php
<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.1.4 -->
<script src="{{ asset('/plugins/jquery/jquery-2.1.4.min.js') }}"></script>
<!-- Bootstrap 3.3.2 JS -->
<script src="{{ asset('/js/bootstrap.min.js') }}" type="text/javascript"></script>
<!-- AdminLTE App -->
<script src="{{ asset('/js/app.min.js') }}" type="text/javascript"></script>
<!-- wysihtml5 -->
<script src="{{ asset('/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}" type="text/javascript"></script>
<!-- select2 -->
<script src="{{ asset('/plugins/select2/select2.min.js') }}" type="text/javascript"></script>
<!-- masked input -->
<script src="{{ asset('/plugins/jquery.maskedinput/jquery.maskedinput.min.js') }}" type="text/javascript"></script>
<!-- google autocomplete -->
<script src="https://maps.googleapis.com/maps/api/js?sensor=true&libraries=geometry,places,visualization&callback=initGoogle" async defer></script>
<script src="{{ asset('/js/libs/admin-geo.js') }}"></script>

<!-- multiselect -->
<script type="text/javascript" src="/plugins/bootstrap-multiselect/js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="/plugins/bootstrap-multiselect/css/bootstrap-multiselect.css" type="text/css"/>

<script type="text/javascript">
  $(function() {
      $('textarea').wysihtml5();
      $('select.select2').select2();
      $('#point_id').multiselect({
        enableFiltering: true,
        buttonWidth: '100%',
        nonSelectedText: 'Select Related Record(s)'
      });
      $('#subscribe_types_id').multiselect({
        enableFiltering: true,
        buttonWidth: '100%',
        nonSelectedText: 'Select Groups Of Recipients'
      });
      $('.j-internal_point_add').click(function () {
        $('#point_id').multiselect($('.j-internal_point_select').is(':disabled') ? 'enable' : 'disable');
        $('.j-internal_point_create').prop("checked", !$('.j-internal_point_create').is(':checked'));
      });
      $("#phone").mask("+7 (999) 999-9999");
      $("#point_phone").mask("+7 (999) 999-9999");
  });
</script>

resources/views/admin/partials/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ Auth::user()->hasAvatar ? '/img/uavatars/u_' . Auth::user()->id . '.png' : '/img/blank_avatar.png'}}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        {{--<!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
        </form>
        <!-- /.search form -->--}}

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">MAIN MENU</li>
            <!-- Optionally, you can add icons to the links -->
            <li class={{ Route::is('admin.home') ? 'active' : '' }}><a href="{{ route('admin.home') }}"><i class='fa fa-link'></i> <span>Dashboard</span></a></li>
            <li class="treeview {{ Route::is('admin.user.*') ? 'active' : '' }}">
                <a href="#"><i class='fa fa-user'></i> <span>Users</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.user.create')}}">Add user</a></li>
                    <li><a href="{{ route('admin.user.index') }}">List users</a></li>
                </ul>
            </li>
            <li class="treeview {{ Route::is('admin.point.*') || Route::is('admin.pointsType.*') ? 'active' : '' }}">
                <a href="#"><i class='fa fa-map-marker'></i> <span>Points</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.pointsType.create')}}">Add pointsType</a></li>
                    <li><a href="{{ route('admin.pointsType.index')}}">List pointsTypes</a></li>
                    <li><a href="{{ route('admin.point.create')}}">Add point</a></li>
                    <li><a href="{{ route('admin.point.index')}}">List points</a></li>
                </ul>
            </li>
            <li class="treeview {{ (Route::is('admin.country.*') || Route::is('admin.region.*')) ? 'active' : '' }}">
                <a href="#"><i class='fa fa-road'></i> <span>Geo</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.country.create')}}">Add Country</a></li>
                    <li><a href="{{ route('admin.country.index')}}">List Countries</a></li>
                    <li><a href="{{ route('admin.region.create')}}">Add region</a></li>
                    <li><a href="{{ route('admin.region.index')}}">List regions</a></li>
                </ul>
            </li>
            <li class="treeview {{ Route::is('admin.subscribe.*') ? 'active' : '' }}">
                <a href="#"><i class='fa fa-road'></i> <span>Subscribe</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.subscribe.create')}}">Subscribe</a></li>
                </ul>
            </li>
        </ul><!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>